waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 20