factory_amr1/controller_manager:
  ros__parameters:
    update_rate: 50

    factory_amr1_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    factory_amr1_luggage_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    factory_amr1_diff_drive_controller:
      type: "diff_drive_controller/DiffDriveController"

factory_amr1/factory_amr1_luggage_controller:
  ros__parameters: 
    joints:
      - luggage_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity    

    state_publish_rate: 50.0
    action_monitor_rate: 50.0

    allow_partial_joints_goal: false
    open_loop_control: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      luggage_joint:
        trajectory: 0.1
        goal: 0.1
      
factory_amr1/factory_amr1_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.62
    wheel_radius: 0.5

    publish_rate: 50.0
    odom_frame_id: "odom"
    base_frame_id: "base_link"
