factory_amr2/controller_manager:
  ros__parameters:
    update_rate: 50

    factory_amr2_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    factory_amr2_luggage_controller:
      type: joint_trajectory_controller/JointTrajectoryController

factory_amr2/factory_amr2_luggage_controller:
  ros__parameters: 
    joints:
      - luggage_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity    

    state_publish_rate: 50.0
    action_monitor_rate: 50.0

    allow_partial_joints_goal: false
    open_loop_control: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      luggage_joint:
        trajectory: 0.1
        goal: 0.1
